#
# ESP32 External Temperature Sensor
#
# https://github.com/jnasholm/ets/tree/main
#
# Main configuration
#
substitutions:
  node_name: ets1
  node_prefix: ET

# Board configuration
esphome:
  project:
    name: "jnasholm.ets"
    version: "0.2"
  name: $node_name
  platform: ESP32
  board: esp32-devkitlipo
#  board: esp32-poe-iso

# Flash write interval
preferences:
  flash_write_interval: 20min

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret hass_api_key

# Enable OTA
ota:
  platform: esphome
  password: !secret ota_password

# Node switches
switch:
  - platform: restart
    name: $node_prefix starta om nod
#  - platform: shutdown
#    name: $node_prefix stäng av nod

# Node uptime
sensor:
  - platform: uptime
    name: $node_prefix drifttid
    icon: mdi:timer-outline
    update_interval: 60s

# Include packages
packages:
  wifi: !include wifi.yaml
#  ethernet: !include ethernet.yaml
  battery: !include battery.yaml
  time: !include time.yaml
  status: !include status.yaml
  outdoor_temp: !include sensors-outdoor_temp.yaml
