#
# ESP32 External Temperature Sensor
#
# https://github.com/jnasholm/ets/tree/main
#
# Main configuration
#
substitutions:
  node_name: et
  node_prefix: ET

# Project configuration
esphome:
  project:
    name: "jnasholm.ets"
    version: "0.3"
  name: $node_name
  friendly_name: $node_prefix
  comment: Outdoor Temperature Sensor
  min_version: 2025.5.0

# Flash write interval
preferences:
  flash_write_interval: 20min

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret hass_api_key

# Enable OTA
ota:
  - platform: esphome
    password: !secret ota_password

# Node switches
switch:
  - platform: restart
    name: Starta om nod
#  - platform: shutdown
#    name: Stäng av nod

# Node uptime
sensor:
  - platform: uptime
    name: Drifttid
    icon: mdi:timer-outline
    update_interval: 60s

# Include packages
packages:
  boardconfig: !include boardconfig.yaml
  battery: !include battery.yaml
  time: !include time.yaml
  status: !include status.yaml
  outdoor_temp: !include sensors-outdoor_temp.yaml
