# Outdoor temperature sensor configuration

# Input configuration outdoor temperatures
#one_wire:
#  - platform: gpio
#    pin: GPIO14
dallas:
  - pin: GPIO14
    id: outdoor_temperature_bus
    update_interval: 20s

# Outdoor temperature
sensor:
#  - platform: dallas_temp
  - platform: dallas
    name: $node_prefix utetemperatur
    id: outdoor_temperature
    accuracy_decimals: 2
    dallas_id: outdoor_temperature_bus
    address: 0x2c0000081d200d28
    resolution: 12
    filters:
      - exponential_moving_average:
          alpha: 0.06
          send_every: 3
          send_first_at: 1
      - heartbeat: 20s
