# Outdoor temperature sensor configuration

# Input configuration outdoor temperatures
one_wire:
  - platform: gpio
    id: outdoor_temperature_bus
    pin: $digital_temp_pin

# Outdoor temperature
sensor:
  - platform: dallas_temp
    name: Utetemperatur
    id: outdoor_temperature
    accuracy_decimals: 2
    update_interval: 20s
    one_wire_id: outdoor_temperature_bus
#    address: 0x2c0000081d200d28
    resolution: 12
    filters:
      - skip_initial: 1
      - exponential_moving_average:
          alpha: 0.06
          send_every: 3
          send_first_at: 1
      - heartbeat: 20s

# Packet transport configuration
udp:

# Broadcast outdoor temperature
packet_transport:
  - platform: udp
    id: transport_output
    update_interval: 10s
    encryption: !secret broadcast_key
    sensors:
      - outdoor_temperature
