# Status configuration

# Controller status indicator
output:
  - platform: ledc
    id: ${node_name}_controller_status
    pin: $controller_led_pin

# System status indicator
light:
  - platform: status_led
    name: Systemstatus
    id: ${node_name}_system_status_indicator
    pin:
      number: $system_led_pin
      inverted: true
# Controller status indicator
  - platform: monochromatic
    name: Reglerstatus
    id: ${node_name}_controller_status_indicator
    output: ${node_name}_controller_status
    effects:
      - pulse:
          name: auto_mode
          transition_length: 0.2s
          update_interval: 0.6s
      - pulse:
          name: manual_mode
          transition_length: 0.2s
          update_interval: 2s

# Controller operational state indication
binary_sensor:
  - platform: template
    id: ${node_name}_controller_state
    lambda: |-
      if ( !isnan(id(outdoor_temperature).state) ) {
        return true;
      } else {
        return false;
      }
    on_press:
      - light.turn_on:
          id: ${node_name}_controller_status_indicator
          effect: auto_mode
    on_release:
      - light.turn_on:
          id: ${node_name}_controller_status_indicator
          effect: manual_mode
